config/routes.rb
Mangocms::Application.routes.draw do

  require 'resque/server'
  mount Resque::Server.new, :at => "/resque"

  devise_for :members, :controllers => { :registrations => "members/registrations", :sessions => "members/sessions", :passwords => "members/passwords"}
  # 首页
  root :to => "main#index"

  #网站前台
  #---------------------------------------
  # 用户登录
  match 'sign_in', :to => 'main#list', :channel_id => 'sign_in'
  # 用户注册
  match 'sign_up', :to => 'main#list', :channel_id => 'sign_up'
  # 弹窗登陆
  match 'pop_sign', :to => 'main#list', :channel_id => 'pop_sign'
  # 文章列表页
  match ':channel_id', :to => 'articles#list', :channel_id => /articles/
  # 文章显示页
  match ':channel_id/:id', :to => 'articles#show', :channel_id => /articles/, :id => /\d+/
  # 留言页面
  match 'questions/:channel_id', :to => 'questions#index', :channel_id => /[a-z_]+/
  # 留言提交
  match 'questions/:channel_id/answer_create', :to => 'questions#answer_create', :channel_id => /[a-z_]+/
  # 留言顶一下提交
  match 'questions/:channel_id/answer_top', :to => 'questions#answer_top', :channel_id => /[a-z_]+/
  # 产品列表页
  match 'product/:channel_id', :to => 'products#list', :channel_id => /product/
  # 产品内容页
  match 'product/:channel_id/:id', :to => 'products#show', :channel_id => /product/, :category_id => /[a-z_]+/, :id => /\d+/
  # 产品验证
  match 'service_verifies/verify', :to => 'service_verifies#verify'
  # 产品验证提交
  match 'service_verifies/verify_save', :to => 'service_verifies#verify_save'
  # 前台商城路由
  match 'shop', :to => 'shop_products#index', :channel_id => "shop"
  # 商城列表页
  match ':channel_id/:category_id', :to => 'shop_products#index', :channel_id => /shop/, :category_id => /\d+/
  # 商城内容页
  match ':channel_id/show/:id', :to => 'shop_products#show', :channel_id => /shop/, :id => /\d+/
  # 商城ajax评论
  match '/shop_products/ajax_comments/:id', :to => 'shop_products#ajax_comments', :id => /\d+/
  # 商城ajax购买记录
  match '/shop_products/ajax_buy_logs/:id', :to => 'shop_products#ajax_buy_logs', :id => /\d+/
  # 订单信息内容页
  match "/shop/:channel_id/:id", :to => 'shop_products#order_info', :channel_id => /order_manager/, :id => /\d+/
  #商城搜索
  match "/shop/index/search/:search_condition", :to => "shop/index#search"
  #招聘信息
  match 'zhaopin/:id', :to => 'zhaopins#show', :channel_id => /\d+/
  #栏目地址
  match '/page/:channel_id', :to => 'main#list', :channel_id => /[a-z_]+/
  #内容地址
  match '/page/:channel_id/:id', :to => 'main#show', :channel_id => /[a-z_]+/, :id => /\d+/

  #---------------------------------------
  #文章
  resources :articles
  #前台支付接口
  namespace :payment do
    resources :alipay do
      collection do
        get :get_page
        get :return_page
        post :notify_page
      end
    end
    resources :alipay_secured do
      collection do
        get :get_page
        post :notify_page
      end
    end
    resources :chinabank do
      collection do
        get :get_page
        post :return_page
        post :notify_page
      end
    end
  end

  #用户详细信息路由
  resources :member_infos do
    collection do
      get :edit_info
      post :update_info
      get :judge_member
      get :judge_useremail
    end
  end

  namespace :shop do
    resources :index do
      collection do
        get :search
      end
    end
    resources :products
    resources :cart
  end

  #前台问答
  resources :questions do
    collection do
      post :answer_create
      post :answer_top
    end
  end


  resources :shop_products do
    collection do
      get :list
      get :order_address
      post :submit_order
      get :my_cart   #我的购物车
      get :add_product   #添加商品
      post :buy_product   #立即购买
      get :modify_cart_info   #修改购物车信息
      post :add_order_address  #添加订单收货地址
      delete :destroy_product       #删除产品
      delete :clear_cart            #清楚购物车
      post :delete_order_address  #删除订单地址
      post :generate_order        #生成订单
      post :comment_save
      get :get_address_info
      get :ajax_comments          #异步获取评论
      get :ajax_buy_logs          #异步获取购买记录
    end
    member do
      get :order_info
    end
  end

  resources :logistics do
    collection do
      get :request_logistics
    end
  end

  # 富文本框路径
  mount Ckeditor::Engine => '/ckeditor'
  #服务验证
  resources :service_verifies do
    collection do
      get :verify
      post :verify_save
    end
  end

  #用户中心
  namespace :my do
    resources :orders do
      member do
        get :delete
        get :show
        get :payment
        get :payment_save
      end
    end
  end
  #——-----------------------------------------————————下面是后台路由——————--------------------————————————-------------------——-——————————-
  #cms后台
  #后台管理路由
  namespace :admin do
    #后台用户路由
    resources :members do
      collection do
        post :search
      end
    end

    #后台问题路由
    resources :questions

    #后台回答
    resources :answers do
      collection do
        get  :search
        post :reply_answer_create
        post :batch_operation
      end
      member do
        get :channel_index
        get :answer_admin
        get :ajax_replay_answer_delete
        get :ajax_replay_answer_auth #异步单个审核

      end
    end

    #商品管理
    resources :shop_categories do
      collection do
        get :tree_info    #左侧树信息
      end
      member do
        get :new_category
      end
    end

    #-------------------------招聘信息---------------------------------------------
    resources  :zhaopins do
      collection do
        get  :search
      end
      member do
        get :channel_index
      end
    end

    #-------------------------信息管理---------------------------------------------
    #产品分类管理
    resources :product_categories do
      collection do
        get :tree_info
      end
      member do
        get :new_child
      end
    end


    #产品管理
    resources :products do
      collection do
        get :delete_attachment
        post :frame_add_attachment
        post :delete_product_image
        get  :search
      end
      member do
        get :channel_index
        get :frame_form
        post :attachment
        post :content_create
        get :upload
        get :product_content
      end
    end

    #服务验证管理
    resources :service_verifies do
      collection do
        get :import
        post :import_save
        get :export
        post :export_save
      end
      member do
        get :operation
      end
    end

    #序列号分类管理
    resources :service_categories do

    end

    #文章路由
    resources :articles do
      collection do
        get  :search
        post :delete_product_image
        post :frame_add_attachment
        get :delete_article_image
      end
      member do
        put :update_article
        get :channel_index
        get :frame_form
        get :new_article
      end
    end

    #自定义页面路由
    resources :custom_pages do
      member do
        get :channel_index
        get :link_channel
      end
    end

    #-----------------------------------------------------------------------------
    #商品路由
    resources :shop_products do
      collection do
        post :frame_add_attachment
        post :delete_product_image
        get  :search
      end
      member do
        get :frame_form
        post :attachment
        get :upload
      end
    end


    #套餐路由
    resources :shop_packages do
      collection do
        get :frame_add_attachment
      end
      member do
        get :frame_form
      end
    end
    #订单路由
    resources :shop_orders do
      collection do
        get :export_xls
      end
      member do
        get :preview
      end
    end

    #后台管理员路由
    resources :managers do
      collection do
        get :login
        post :check_login
        get :exists_attach
      end
      member do
        get :modify_password
        post :update_password
        get :logout
      end
    end

    #后台全局变量分类路由
    resources :global_variable_categories do
      collection do
        post :sort
      end
    end

    #后台全局变量路由
    resources :global_variables do
      member do
        get :delete_var
        get :new_image
        get :edit_image
        post :create_image
        post :update_image
      end
      collection do
        post :update_all
        get :exists_attach
      end
    end

    #后台友情链接路由
    resources :friendly_websites

    #后台首页
    resources :main
    #模板管理
    resources :templates do
      member do
        get :default_template
        get :list
      end
    end
    #模板资源文件管理
    resources :skins do
      collection do
        get :upload_file
        post :upload
        get :delete
        get :edit_file
        post :update_file
      end
    end

    #栏目管理
    resources :channels do
      member do
        get :new_child
        get :check_destroy
      end
      collection do
        get :exists_attach
        get :tree_info
        get :template_json_info
      end
    end
    #系统模型管理
    resources :info_models

    #评论管理
    resources :comments do
      collection do
        get :batch_act
      end
    end
  end
end

app/models/global_variable_category.rb
#encoding: UTF-8
class GlobalVariableCategory < ActiveRecord::Base
  belongs_to :parent,
    :class_name  => 'GlobalVariableCategory'
  has_many :children, :class_name => "GlobalVariableCategory", :foreign_key => "parent_id", :dependent => :destroy, :order => "position asc, id asc"
  has_many :global_variables, :dependent => :destroy

  #配置级别
  LEVEL_HIGHEST = 100	#高级，不可删改
  LEVEL_NORMAL = 200	#中级，只可以改
  LEVEL_LOWER = 300		#低级，可增删改

  #根据父id获取分类
  scope :by_parent_id, lambda{|parent_id| where("parent_id = ?", parent_id.to_i).order("position asc, id asc")}
  #根据配置级别获取
  scope :by_level, lambda{|level| where("level = ?", level.to_i).order("position asc, id asc")}

  #--------------------验证---------------------
  validates :name,   :presence => {:message => "名称不能为空"}

  #--------------------过滤器---------------------
  before_destroy{
    if self.level < GlobalVariableCategory::LEVEL_LOWER
      raise "配置级别太高不可删除"
    end
  }

  # 下拉分类列表
  #
  # 作者: 赵晓龙
  # 最后更新时间: 2012-05-10
  #
  # ==== 参数
  # * <tt>parent_id</tt> - 初始上级id
  # * <tt>depth</tt> - 递归深度
  # * <tt>level</tt> - 配置级别
  #
  # ==== 示例
  #   GlobalVariableCategory.recursive_get_options
  #
  # ==== 返回
  #   Hash
  #
  def self.get_options(parent_id = 0, level = LEVEL_LOWER)
    categories = by_level(level)
     #关系数组转换成对象数组
    categories = categories.to_a
    return recursive_get_options(parent_id, categories)
  end
  
  def self.recursive_get_options(parent_id, categories)
    options = Hash.new
    categories.select{|category| category.parent_id == parent_id}.each do |category|
      child_categories = categories.select{|child_category| child_category.parent_id == category.id}
      if child_categories.present?
        options[category.name] = recursive_get_options(category.id, child_categories)
      else
        if category.depth == 0
          options["根分类"] = {category.name => category.id.to_s}
        else
          options[category.name] = category.id.to_s
        end
      end
    end
    return options
  end

  # 获取分类列表
  #
  # 作者: 赵晓龙
  # 最后更新时间: 2012-05-21
  #
  # ==== 参数
  # * <tt>level</tt> - 配置级别
  #
  # ==== 示例
  #   GlobalVariableCategory.get_list(0)
  #
  # ==== 返回
  #   Array[GlobalVariableCategory]
  #
  def self.get_list(level = LEVEL_LOWER)
    list = Array.new
    categories = by_level(level)
    #关系数组转换成对象数组
    categories = categories.to_a
    recursive_get_list(0, list, categories)
    return list
  end

  # 递归获取分类列表
  #
  # 作者: 赵晓龙
  # 最后更新时间: 2012-05-21
  #
  # ==== 参数
  # * <tt>parent_id</tt> - 初始上级id
  # * <tt>list</tt> - 结果列表
  # * <tt>categories</tt> - 当前分类列表
  #
  # ==== 示例
  #   GlobalVariableCategory.recursive_get_list(parent_id, list, categories)
  #
  # ==== 返回
  #   Array[GlobalVariableCategory]
  #
  def self.recursive_get_list(parent_id, list, categories)
    categories.select{|category| category.parent_id == parent_id}.each do |category|
      list << category
      categories.delete(category)
      recursive_get_list(category.id, list, categories)
    end
    
  end

  # 获取关联深度的名称
  #
  # 作者: 赵晓龙
  # 最后更新时间: 2012-05-28
  #
  # ==== 示例
  #   GlobalVariableCategory.depth_name
  #
  # ==== 返回
  #   string
  #
  def depth_name
    return_str = "┣"
    return return_str + "━" * self.depth.to_i + self.name
  end


end

app/controllers/admin/global_variable_categories_controller.rb
#encoding: UTF-8
class Admin::GlobalVariableCategoriesController < Admin::BaseController
  # 首页
  #
  # 作者：赵晓龙
  # 更新时间：2012-05-28
  def index
    #分类列表
    @categories = GlobalVariableCategory.get_list
  end

  # 新建页
  #
  # 作者：赵晓龙
  # 更新时间：2012-05-28
  def new
    @category = GlobalVariableCategory.new
  end

  # 创建分类
  #
  # 作者：赵晓龙
  # 更新时间：2012-05-28
  def create
    @category = GlobalVariableCategory.new(params[:global_variable_category])
    @category.level = GlobalVariableCategory::LEVEL_LOWER
    @category.depth = @category.parent.present? ? @category.parent.depth + 1 : 0
    if @category.save
      flash[:success] = "添加成功！"
      redirect_to admin_global_variable_categories_path
    else
      flash.now[:error] = "添加失败，修改后请重新提交！"
      render :action => :new
    end
  end

  # 编辑页
  #
  # 作者：赵晓龙
  # 更新时间：2012-05-28
  def edit
    begin
      @category = GlobalVariableCategory.find(params[:id])
      render :new
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "对象不存在！"
      redirect_to admin_global_variable_categories_path
    end
  end

  # 更新
  #
  # 作者：赵晓龙
  # 更新时间：2012-05-28
  def update
    begin
      category = GlobalVariableCategory.find(params[:id])
      if category.update_attributes(params[:global_variable_category])
        category.update_attribute(:depth, category.parent.present? ? category.parent.depth + 1 : 0)
        flash[:success] = "保存成功！"
        redirect_to admin_global_variable_categories_path
      else
        flash.now[:error] = "保存失败，修改后请重新提交！"
        render :action => :new
      end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "对象不存在！"
      redirect_to admin_global_variable_categories_path
    end
  end

  # 删除变量
  #
  # 作者：赵晓龙
  # 更新时间：2012-05-28
  def destroy
    begin
      @category = GlobalVariableCategory.by_level(GlobalVariableCategory::LEVEL_LOWER).find(params[:id])
      if @category.global_variables.blank?
        if @category.destroy
          flash[:success] = "变量删除成功！"
        else
          flash[:error] = "变量删除失败！"
        end
      else
        flash[:error] = "还有设置信息，分类不可删除！"
      end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "对象不存在！"
    rescue RuntimeError => error
      flash[:error] = error.message
    end
    redirect_to admin_global_variable_categories_path
  end

  # 排序
  #
  # 作者：赵晓龙
  # 更新时间：2012-05-29
  def sort
    @categories = GlobalVariableCategory.by_level(GlobalVariableCategory::LEVEL_LOWER).all
    @categories.each do |category|
      category.position = params['obj'].index(category.id.to_s) + 1
      category.save
    end
    render :nothing => true
  end
end

app/helpers/admin/global_variable_categories_helper.rb
module Admin::GlobalVariableCategoriesHelper
end

app/views/admin/global_variable_categories/_form.html.erb
<div class="s-input">
  <%= f.label :parent_id, "*所属分类：" %>
  <br />
  <%= f.select :parent_id, options_for_select(GlobalVariableCategory.by_parent_id(0).by_level(GlobalVariableCategory::LEVEL_LOWER).delete_if{|category| category == @category}.map{|category| [category.name, category.id]}.unshift(["根分类", 0]), @category.parent_id), {:include_blank => false} %>
</div>
<br />

<div class="s-input">
  <%= f.label :name, "*分类名称：" %>
  <br />
  <%= f.text_field :name %>
</div>
<br />

<div class="s-input">
  <%= f.label :description, "描述信息：" %>
  <br />
  <%= f.text_area :description, :size => "70x10" %>
</div>
<br />

<div class="s-input">
  <%= f.submit "保存" %>
</div>


<br />

app/views/admin/global_variable_categories/index.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "system"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/system"%>
<% end %>
<div class="gm-tabs s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      配置分类管理
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-tabs-head">
    <a href="#"  class="current">分类列表</a>
  </div>
  <div class="gm-tabs-content current">
    <div class="gm-toolbar">
      <ul>
        <li><%=link_to "添加分类", new_admin_global_variable_category_path ,:title => "添加分类" %></li>
      </ul>
    </div>
    <div class="s-table">
      <table>
        <thead>
          <tr>
            <th style="width:50px;">选项</th>
            <th>分类名</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody id="objs">
          <% @categories.each do |category|  %>
            <tr id="obj_<%= category.id %>">
              <td>
                <div class="s-input">
                  <input type="checkbox" value="<%= category.id%>" />
                </div>
              </td>
              <td> <%= link_to category.depth_name, edit_admin_global_variable_category_path(category)  %>  </td>
              <td class="edit">
                <%= link_to image_tag("icon/edit.png"), edit_admin_global_variable_category_path(category),:title => "编辑" %>
                <%= link_to image_tag("icon/delete.png"), admin_global_variable_category_path(category), :method => :delete ,:confirm => "配置项也会被删除，你确定要删除吗？" ,:title => "删除"%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
 $(function(){
    sortList("objs","tr");//调用排序方法，对post对行排序
})

//排序方法,可实现多次调用，obj:要排序的model复数名，item：排序元素，jqeury官方文发写的是对li进行排序，但可以对表格排序，具体访谈录请参考jquery ui文档
function sortList(obj,item)
{
  $('#'+obj).sortable({
    axis: 'y',
    dropOnEmpty: false,
    //handle: '.handle',
    cursor: 'crosshair',
    items: item,
    opacity: 0.4,
    scroll: true,
    update: function(){
      $.ajax({
        type: 'post',
        data: $('#'+obj).sortable('serialize'),
        dataType: 'script',
        complete: function(request){
          $('#'+obj).effect('highlight');
          },
          url: "<%= sort_admin_global_variable_categories_path%>"
        });
     }
  });
}
</script>

app/views/admin/global_variable_categories/new.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "system"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/system"%>
<% end %>

<div class="gm-bloc s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      <%= @category.new_record? ? "添加" : "编辑" %>属性
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-bloc-body">
    <%= form_for @category, :url => (@category.new_record? ? admin_global_variable_categories_path : admin_global_variable_category_path(@category)), :html =>{:id => "global_variable_category"} do |f| %>
      <%= render :partial =>"form", :locals =>{:f => f } %>
    <% end %>
  </div>
</div>

<%= content_for :head do   %>
  <script type ="text/javascript">

    $(function(){
      $("#global_variable_category").validate({
        //debug:true,　//测试时打开
        rules: {
          "global_variable_category[name]": {
            required:true,
            rangelength:[2,30]
          }
        },
        messages:{
          "global_variable_category[name]": {
            required: "分类名不能为空",
            rangelength:"描述应在2-30个汉字"
          }
        },
        submitHandler:function(form){
          $(form).hide().data('submiting','true');
          var loading = $('<p>正在提交，请稍后...</p>');
          $(form).after(loading);
          form.submit();
        }
      });
    });

  </script>

<% end %>