config/routes.rb
Mangocms::Application.routes.draw do

  require 'resque/server'
  mount Resque::Server.new, :at => "/resque"

  devise_for :members, :controllers => { :registrations => "members/registrations", :sessions => "members/sessions", :passwords => "members/passwords"}
  # 首页
  root :to => "main#index"

  #网站前台
  #---------------------------------------
  # 用户登录
  match 'sign_in', :to => 'main#list', :channel_id => 'sign_in'
  # 用户注册
  match 'sign_up', :to => 'main#list', :channel_id => 'sign_up'
  # 弹窗登陆
  match 'pop_sign', :to => 'main#list', :channel_id => 'pop_sign'
  # 文章列表页
  match ':channel_id', :to => 'articles#list', :channel_id => /articles/
  # 文章显示页
  match ':channel_id/:id', :to => 'articles#show', :channel_id => /articles/, :id => /\d+/
  # 留言页面
  match 'questions/:channel_id', :to => 'questions#index', :channel_id => /[a-z_]+/
  # 留言提交
  match 'questions/:channel_id/answer_create', :to => 'questions#answer_create', :channel_id => /[a-z_]+/
  # 留言顶一下提交
  match 'questions/:channel_id/answer_top', :to => 'questions#answer_top', :channel_id => /[a-z_]+/
  # 产品列表页
  match 'product/:channel_id', :to => 'products#list', :channel_id => /product/
  # 产品内容页
  match 'product/:channel_id/:id', :to => 'products#show', :channel_id => /product/, :category_id => /[a-z_]+/, :id => /\d+/
  # 产品验证
  match 'service_verifies/verify', :to => 'service_verifies#verify'
  # 产品验证提交
  match 'service_verifies/verify_save', :to => 'service_verifies#verify_save'
  # 前台商城路由
  match 'shop', :to => 'shop_products#index', :channel_id => "shop"
  # 商城列表页
  match ':channel_id/:category_id', :to => 'shop_products#index', :channel_id => /shop/, :category_id => /\d+/
  # 商城内容页
  match ':channel_id/show/:id', :to => 'shop_products#show', :channel_id => /shop/, :id => /\d+/
  # 商城ajax评论
  match '/shop_products/ajax_comments/:id', :to => 'shop_products#ajax_comments', :id => /\d+/
  # 商城ajax购买记录
  match '/shop_products/ajax_buy_logs/:id', :to => 'shop_products#ajax_buy_logs', :id => /\d+/
  # 订单信息内容页
  match "/shop/:channel_id/:id", :to => 'shop_products#order_info', :channel_id => /order_manager/, :id => /\d+/
  #商城搜索
  match "/shop/index/search/:search_condition", :to => "shop/index#search"
  #招聘信息
  match 'zhaopin/:id', :to => 'zhaopins#show', :channel_id => /\d+/
  #栏目地址
  match '/page/:channel_id', :to => 'main#list', :channel_id => /[a-z_]+/
  #内容地址
  match '/page/:channel_id/:id', :to => 'main#show', :channel_id => /[a-z_]+/, :id => /\d+/

  #---------------------------------------
  #文章
  resources :articles
  #前台支付接口
  namespace :payment do
    resources :alipay do
      collection do
        get :get_page
        get :return_page
        post :notify_page
      end
    end
    resources :alipay_secured do
      collection do
        get :get_page
        post :notify_page
      end
    end
    resources :chinabank do
      collection do
        get :get_page
        post :return_page
        post :notify_page
      end
    end
  end

  #用户详细信息路由
  resources :member_infos do
    collection do
      get :edit_info
      post :update_info
      get :judge_member
      get :judge_useremail
    end
  end

  namespace :shop do
    resources :index do
      collection do
        get :search
      end
    end
    resources :products
    resources :cart
  end

  #前台问答
  resources :questions do
    collection do
      post :answer_create
      post :answer_top
    end
  end


  resources :shop_products do
    collection do
      get :list
      get :order_address
      post :submit_order
      get :my_cart   #我的购物车
      get :add_product   #添加商品
      post :buy_product   #立即购买
      get :modify_cart_info   #修改购物车信息
      post :add_order_address  #添加订单收货地址
      delete :destroy_product       #删除产品
      delete :clear_cart            #清楚购物车
      post :delete_order_address  #删除订单地址
      post :generate_order        #生成订单
      post :comment_save
      get :get_address_info
      get :ajax_comments          #异步获取评论
      get :ajax_buy_logs          #异步获取购买记录
    end
    member do
      get :order_info
    end
  end

  resources :logistics do
    collection do
      get :request_logistics
    end
  end

  # 富文本框路径
  mount Ckeditor::Engine => '/ckeditor'
  #服务验证
  resources :service_verifies do
    collection do
      get :verify
      post :verify_save
    end
  end

  #用户中心
  namespace :my do
    resources :orders do
      member do
        get :delete
        get :show
        get :payment
        get :payment_save
      end
    end
  end
  #——-----------------------------------------————————下面是后台路由——————--------------------————————————-------------------——-——————————-
  #cms后台
  #后台管理路由
  namespace :admin do
    #后台用户路由
    resources :members do
      collection do
        post :search
      end
    end

    #后台问题路由
    resources :questions

    #后台回答
    resources :answers do
      collection do
        get  :search
        post :reply_answer_create
        post :batch_operation
      end
      member do
        get :channel_index
        get :answer_admin
        get :ajax_replay_answer_delete
        get :ajax_replay_answer_auth #异步单个审核

      end
    end

    #商品管理
    resources :shop_categories do
      collection do
        get :tree_info    #左侧树信息
      end
      member do
        get :new_category
      end
    end

    #-------------------------招聘信息---------------------------------------------
    resources  :zhaopins do
      collection do
        get  :search
      end
      member do
        get :channel_index
      end
    end

    #-------------------------信息管理---------------------------------------------
    #产品分类管理
    resources :product_categories do
      collection do
        get :tree_info
      end
      member do
        get :new_child
      end
    end


    #产品管理
    resources :products do
      collection do
        get :delete_attachment
        post :frame_add_attachment
        post :delete_product_image
        get  :search
      end
      member do
        get :channel_index
        get :frame_form
        post :attachment
        post :content_create
        get :upload
        get :product_content
      end
    end

    #服务验证管理
    resources :service_verifies do
      collection do
        get :import
        post :import_save
        get :export
        post :export_save
      end
      member do
        get :operation
      end
    end

    #序列号分类管理
    resources :service_categories do

    end

    #文章路由
    resources :articles do
      collection do
        get  :search
        post :delete_product_image
        post :frame_add_attachment
        get :delete_article_image
      end
      member do
        put :update_article
        get :channel_index
        get :frame_form
        get :new_article
      end
    end

    #自定义页面路由
    resources :custom_pages do
      member do
        get :channel_index
        get :link_channel
      end
    end

    #-----------------------------------------------------------------------------
    #商品路由
    resources :shop_products do
      collection do
        post :frame_add_attachment
        post :delete_product_image
        get  :search
      end
      member do
        get :frame_form
        post :attachment
        get :upload
      end
    end


    #套餐路由
    resources :shop_packages do
      collection do
        get :frame_add_attachment
      end
      member do
        get :frame_form
      end
    end
    #订单路由
    resources :shop_orders do
      collection do
        get :export_xls
      end
      member do
        get :preview
      end
    end

    #后台管理员路由
    resources :managers do
      collection do
        get :login
        post :check_login
        get :exists_attach
      end
      member do
        get :modify_password
        post :update_password
        get :logout
      end
    end

    #后台全局变量分类路由
    resources :global_variable_categories do
      collection do
        post :sort
      end
    end

    #后台全局变量路由
    resources :global_variables do
      member do
        get :delete_var
        get :new_image
        get :edit_image
        post :create_image
        post :update_image
      end
      collection do
        post :update_all
        get :exists_attach
      end
    end

    #后台友情链接路由
    resources :friendly_websites

    #后台首页
    resources :main
    #模板管理
    resources :templates do
      member do
        get :default_template
        get :list
      end
    end
    #模板资源文件管理
    resources :skins do
      collection do
        get :upload_file
        post :upload
        get :delete
        get :edit_file
        post :update_file
      end
    end

    #栏目管理
    resources :channels do
      member do
        get :new_child
        get :check_destroy
      end
      collection do
        get :exists_attach
        get :tree_info
        get :template_json_info
      end
    end
    #系统模型管理
    resources :info_models

    #评论管理
    resources :comments do
      collection do
        get :batch_act
      end
    end
  end
end

app/controllers/admin/shop_products_controller.rb
#encoding: UTF-8
class Admin::ShopProductsController < Admin::BaseController
  #首页
  #
  #作者：赵晓龙
  #更新时间：2012-3-13
  def index
    @shop_products = ShopProduct.ct_desc
    @shop_products = @shop_products.where(:shop_category_id => params[:category_id]) if params[:category_id]
    @shop_products = @shop_products.page(params[:page]).per(20)
    render :layout => false if request.headers["X-Requested-With"]
  end

  #创建页
  #
  #作者：赵晓龙
  #更新时间：2012-3-13
  def new
    @root_categories = ShopCategory.parent_id(1)
    @categories = {}
    @shop_product = ShopProduct.new
    @shop_product.shop_product_type = 0
    @shop_product.product_status = 1     #默认为上架模式
    render :layout => "iframe"
  end

  #保存
  #
  #作者：赵晓龙
  #更新时间：2012-3-13
  def create
    @shop_product = ShopProduct.new(params[:shop_product])
    if @shop_product.save
      flash[:success] = "创建成功"
      redirect_to :action => "edit" , :id => @shop_product.id, :anchor => "upload_img"
    else
      flash[:error] = @shop_product.errors.messages.map{|m| m[1]}.join(",")
      redirect_to :back
    end
  end

  #编辑页
  #
  #作者：赵晓龙
  #更新时间：2012-3-13
  def edit
    @root_categories = ShopCategory.parent_id(1)
    @shop_product = ShopProduct.find(params[:id])
    @categories = @shop_product.shop_product_category_relations.map{|relation| relation.shop_category_id}
    #如果关联该商品的产品已经被删除 页面将不会再选择产品
    @not_product = true  unless @shop_product.product 
    #商品内容
    @product_content = @shop_product.product_content  || @shop_product.build_product_content
    @images = @shop_product.attached_pictures
    render :layout => "iframe"
  end

  #更新
  #
  #作者：赵晓龙
  #更新时间：2012-3-13
  def update
    @shop_product = ShopProduct.find(params[:id])
    ShopProduct.transaction do 
     unless   @shop_product.update_attributes(params[:shop_product])
      flash[:error] = "更新失败"
      render :back and return 
     end
     old_categorids = @shop_product.shop_product_category_relations.map{|relation| relation.shop_category_id}
      new_categories = params[:categories] && params[:categories].class == Array ? params[:categories].map{|id| id.to_i} : Array.new
      #删掉取消选择的项
      @shop_product.shop_product_category_relations.where("shop_category_id in (?) AND shop_product_id = ?", old_categorids - new_categories, @shop_product.id).destroy_all
      #增加新选择的项
      (new_categories - old_categorids).each do |category_id|
        @shop_product.shop_product_category_relations.create(:shop_category_id => category_id) if category_id.to_i > 0
      end
      if @shop_product.product_content
          @shop_product.product_content.update_attributes(params[:product_content]) 
      else
          @shop_product.build_product_content(params[:product_content])
      end
      @shop_product.save
      flash[:success] = "商品内容更新成功"
    end
    redirect_to upload_admin_shop_product_path(@product,:iframe => params[:iframe])
  end

  #删除
  #
  #作者：赵晓龙
  #更新时间：2012-3-20
  def destroy
    @shop_product = ShopProduct.find(params[:id])
    succ =  @shop_product.destroy
    respond_to do |format|
      format.js{
        if succ
          render :js => "window.parent.load_content();"
        else
          render :js => "alert('删除有错误');"
        end
      }
      format.html{
        redirect_to :back
      }
    end
   
  end


  #上传附件图片页面  iframe 里的页面
  #
  # 作者: 佟立家
  # 最后更新时间: 2012-03-30
  #
  def frame_form
    @shop_product = ShopProduct.find  params[:id]
    @imageId =  AttachedPicture.find(params[:imageId])  if params[:imageId].present?
    @attachedpictrue =  AttachedPicture.new params[:attachedpictrue]
    render :layout => false
  end



  # iframe 里的页面
  #导步上传附件图片
  #
  # 作者: 佟立家
  # 最后更新时间: 2012-03-30
  #
  def frame_add_attachment
    @shop_product =  ShopProduct.find(params[:id])
    @shop_product.attached_pictures.build(params[:attached_picture])
    if @shop_product.save
      redirect_to frame_form_admin_shop_product_path(params[:id],:imageId => @shop_product.attached_pictures.last.id)
    else
      render :back
    end
  end

  #添加附件图片第二步
  #
  # 作者: 佟立家
  # 最后更新时间: 2012-03-30
  #
  def attachment
    @shop_product = ShopProduct.find params[:id]
    if params[:product_imgs].present? && params[:product_imgs].size > 0
      ProductAttachment.add_attachment_thumb(@shop_product,params[:product_imgs])
      flash[:success] =  "创建成功"
    end
    render :text => "<script>window.parent.$.jqmClose();window.parent.load_content();alert('保存成功');</script>" and return
  end

  #产品添加第三步，上传产品小图
  #
  # 作者: 佟立家
  # 最后更新时间: 2012-03-30
  #
  def upload
    @shop_product = ShopProduct.find params[:id]
    #是iframe里
    render :layout => "iframe"
  end



  #删除产品图片
  #
  # 作者: 佟立家
  # 最后更新时间: 2012-03-30
  #
  def delete_product_image
    image = AttachedPicture.find_by_id params[:id]
    if  image.destroy
      render :js => "alert('删除成功');"
    else
      render :js => "alert('删除失败');", :status => 404
    end
  end
end

app/helpers/admin/shop_products_helper.rb
module Admin::ShopProductsHelper
end

app/helpers/shop_products_helper.rb
module ShopProductsHelper
end

app/views/admin/shop_products/attachment.html.erb
 
<html>
  <head></head>
  <body>
    <script type ="text/javascript"> 
      (function(){
<% if @type %>
      window.parent.$.jqmClose();
      window.parent.load_content();
      alert('产品保存成功了');
<% else %>
      alert('保存产品出错了');
      histoty.back();
<% end %>
  })(); 
    </script>
  </body>
</html>

app/views/admin/shop_products/edit.html.erb
<div class="gm-bloc s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      编辑商品
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-bloc-body">
    <% content_for :error_message do %>
        <br/>
        <% error_messages(@shop_product).each do |err| %>
            <%= err %>
            <br/>
        <% end %>
    <% end %>
    <%= simple_form_for @shop_product, :url => admin_shop_product_path, :remote => true, :defaults => {:input_html => {:id => "product_form"}} do |f| %>
        <%= render :partial =>"form", :locals =>{:f => f} %>
    <% end %>
  </div>
</div>


<%= content_for :head do %>
    <script type="text/javascript">
        $(function() {
            $("#update_attachment").click(function(e) {
                if (e.target.nodeName == 'SPAN') {
                    if (e.target.className == 'addon-img-insert') {
                        CKEDITOR.instances.product_content_content.insertHtml('<img src="' + $(e.target).parent().find('img').attr('src') + '" />');
                    }

                    if (e.target.className == 'addon-img-delete') {

                        $.ajax({
                            type: "POST",
                            url: "<%=delete_product_image_admin_shop_products_path %> ",
                            data: "id=" + e.target.getAttribute('addonId'),
                            success:function() {
                                $(e.target).parent().remove();
                            }
                        });

                    }
                }
            });
        });

        $(function() {
            $("#edit_shop_product_<%= @shop_product.id %>").validate({

                 rules: {
                 "shop_product[product_id]": {
                         required: true
                          }
                   },
                  messages:{
                  "shop_product[product_id]": {
                  required:"产品不能为空"
                    }
                  },
                submitHandler:function(form) {
                    $(form).hide().data('submiting', 'true');
                    var loading = $('<p> <%= image_tag("/images/loading.gif") %>正在提交，请稍后...</p>');
                    $(form).after(loading);
                    form.submit();
                }
            });
        });


    </script>
<% end %>

app/views/admin/shop_products/frame_form.erb
<!DOCTYPE html>
<html>
  <head>
    <title>芒果CMS系统</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- description -->
    <meta name="description" content="芒果CMS系统" />
     <%= javascript_include_tag "admin.js" %>
    <style type="text/css">
      body{margin:0;padding:0;font-size: 12px;}
    </style>
    <script type ="text/javascript">
        <%if @imageId.present? %>
         var imgInfo = "<%= @imageId.thumb.url %> <%= @imageId.id %>";
        <% else %>
          var imgInfo = "";
        <% end %>
          
        if($.trim(imgInfo)){
          var imgInfoAry = imgInfo.split(' ');
          var url = imgInfoAry[0];
          var imgId = imgInfoAry[1];

          var doc = window.parent.document;

          var imgWrapper = doc.createElement('div');
          imgWrapper.className = 'addon-img-wrapper';
          imgWrapper.appendChild(createImg(url,imgId,doc));

          var insertImg = doc.createElement('span');
          insertImg.innerHTML = '插入';
          insertImg.className = 'addon-img-insert';
          insertImg.setAttribute('addonId',imgId);

          var deleteImg = doc.createElement('span');
          deleteImg.innerHTML = '删除';
          deleteImg.className = 'addon-img-delete';
          deleteImg.setAttribute('addonId',imgId);

          imgWrapper.appendChild(insertImg);
          imgWrapper.appendChild(deleteImg);
         doc.getElementById('update_attachment').appendChild(imgWrapper);
        }

        function createImg(url,id,doc){
          var img = doc.createElement('img');
        img.src = url;
          img.setAttribute('addonId',id);
          return img;
        }

        $(document).ready(function(){
          $('.fsubmit').css('display','none');

          $('form').submit(function(){
            $(this).hide();
            $('<span>正在上传图片...</span>').appendTo(document.body);
          });

          $('.fileInput').change(function(e){
            var names = this.value.split('.');
            var extName = names[names.length-1].toLowerCase();
            var patterns = {'jpg':true,'gif':true,'png':true};
            if(patterns[extName]){
              $('.fsubmit').css('display','');
            }else{
              $('.fsubmit').css('display','none');
              alert('不支持的文件格式');
            }
          })

        })
    </script>
  </head>
  <body>
    <%= form_for @attachedpictrue, :url => frame_add_attachment_admin_shop_products_path(:id => @shop_product.id), :html => {:method => :post, :multipart => true} do |f|  %>
      选择图片(只支持JPG,GIF,PNG格式)：<%= f.file_field :thumb, :class => "fileInput" %>
      <%=f.submit "上传" , :class => "fsubmit" %>
    <% end %>
   
  </body>
</html>

app/views/admin/shop_products/index.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "shop_category"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/shop_category"%>
<% end %>

<div class="gm-tabs s-h-wrapper">
  <div class="gm-tabs-head">
    <a href="#"  class="current">商品信息管理</a>
  </div>
  <div class="gm-tabs-content current">
    <div class="gm-toolbar">
      <ul>
        <li><%= link_to "添加商品", "" , "data-iframe-src" => new_admin_shop_product_path(:category_id=>params[:category_id]), :title => "添加商品" , :class => "add-shop-category" %></li>
      </ul>
    </div>
    <div class="s-table">
      <table>
        <thead>
          <tr>
            <th width="50">选项</th>
            <th width="50">序号</th>
            <th width="150">产品名称</th>
            <th width="150">商品名称</th>
            <th width="80">价格</th>
            <th width="80">市场价格</th>
            <th width="50">库存量</th>
            <th width="80">上架状态</th>
            <th width="110">更新时间</th>
            <th width="100">操作</th>
          </tr>
        </thead>
        <tbody>
          <% @shop_products.each do |product| %>
            <tr>
              <td>
                <div class="s-input">
                  <input type="checkbox" value="<%=  product.id%>" />
                </div>
              </td>
              <td><%= product.id  %> </td>
              <td><%= product.product ? product.product.name : "产品不存在" %> </td>
              <td>
                <%= link_to product.name, edit_admin_shop_product_path(product), "data-iframe-src" => edit_admin_shop_product_path(product), :title => "编辑", :class => "add-shop-category"%>
              </td>
              <td><%= currency_price(product.price)  %> </td>
              <td><%= currency_price(product.market_price)  %> </td>
              <td><%= product.stock  %> </td>
              <td><%= ShopProduct.product_status_cn(product.product_status)  %> </td>
              <td><%= current_time_format(product.updated_at)%></td>
              <td class="edit">
                <%= link_to image_tag("icon/pic.png"), "" , "data-iframe-src" => upload_admin_shop_product_path(product, :iframe => true ),:title => "图片管理", :class => "add-shop-category" %>
                <%= link_to image_tag("icon/edit.png"), "" , "data-iframe-src" => edit_admin_shop_product_path(product), :title => "编辑", :class => "add-shop-category"%>
                <%= link_to image_tag("icon/delete.png"), admin_shop_product_path(product), :remote => true, :method => :delete ,:confirm => "你确定要删除吗？" %>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>

    <div class="gm-pagination">
      <%= paginate @shop_products %>
    </div>

  </div>
</div>

<script type="text/javascript">
  $(function(){
    // Document is ready
    $('.gm-tabs').jqtab();
    $('#validBeforePicker,#validAfterPicker').datepick({
      onSelect: customRange});
  });


  function customRange(dates) {
    if (this.id == 'validBeforePicker') {
      $('#validAfterPicker').datepick('option', 'minDate', dates[0] || null);
    }
    else {
      $('#validBeforePicker').datepick('option', 'maxDate', dates[0] || null);
    }
  }

  $.jqmIframe({
    overlay: 70,
    trigger: '.add-shop-category',
    onLoad : $.jqmFullWindow
  });

  function load_content(){
    $('#tree_load_content').load("/admin/shop_products<%='?page=params[:page]' if params[:page]%>");
  }

  $().ready(function(){
    $(".jqmClose").click(function(){
      load_content();
    });
  })


</script>

app/views/admin/shop_products/new.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "shop"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/shop"%>
<% end %>

<div class="gm-bloc s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      添加商品
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-bloc-body">
    <% content_for :error_message do %>
      <br />
      <% error_messages(@shop_product).each do |err| %>
        <%= err %><br />
      <% end %>
    <% end %>
    <%= simple_form_for @shop_product, :url => admin_shop_products_path, :defaults => {  :input_html => {:id => "product_form"} } do |f| %>
      <%= render :partial =>"form", :locals =>{:f => f } %>
    <% end %>
  </div>
</div>

<%=content_for :head do%>
  <script type ="text/javascript">
    $(function(){
      $("#new_shop_product").validate({
        //debug:true,　//测试时打开
        rules: {
          "shop_product[description]": {
            rangelength:[2,200]
          }
        },
        messages:{
          "shop_product[description]": {
            rangelength:"描述应在2-200个汉字"
          }
        },
        submitHandler:function(form){
          $(form).hide().data('submiting','true');
          var loading = $('<p> <%= image_tag("/images/loading.gif") %>正在提交，请稍后...</p>');
          $(form).after(loading);
          form.submit();
        }
      });
    });
  </script>
<% end %>

app/views/admin/shop_products/upload.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "shop_category"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/shop_category"%>
<% end %>
<div class="gm-bloc s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      缩略图管理
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-bloc-body">
    <%= form_for  @shop_product, :url => attachment_admin_shop_product_path(@shop_product), :html => { :multipart => true, :method => :post }  do |f| %>
      <div class="s-input">
        商品图片管理（商品小图）<br />
        图片比例: 1 x 1 <br />
        图片应大于 368 X 368<br />
        上传缩略图：<input type="file" name="product_imgs[]"/>
        <span id ="thumb" ></span> <br/> &nbsp;&nbsp;&nbsp;
        <%= link_to "添加", "#", :onclick =>"add_thumb();return false;" %>
        <%@shop_product.product_attachments.each do |attachment|%>
          <div id="img_<%=attachment.id%>">
            <span>浏览：</span>
            <span><img src="<%=attachment.thumb.url(:s1)%>" height="60"/>&nbsp;<a href="javascript:removeimg('<%=attachment.id%>');"  onclick = "return (confirm('确定删除此图片吗?'))">删除</a></span>
          </div>
        <%end%>
      </div>
      <br />
      <div class="s-input">
        <%= f.submit "保存" %>
      </div>
      <br />
    <% end %>
  </div>
</div>

<%=content_for :head do%>
  <script type ="text/javascript">
    $(function(){
      $("#new_product").validate({
        //debug:true,　//测试时打开
        rules: {
        },
        messages:{
        },
        submitHandler:function(form){
          $(form).hide().data('submiting','true');
          var loading = $('<p> <%= image_tag("/images/loading.gif") %>正在提交，请稍后...</p>');
          $(form).after(loading);
          form.submit();
        }
      });
    });

    var img_index=0;
    function add_thumb(){
      var html="<div id=\"thumb_"+img_index+"\">上传缩略图：<input type=\"file\" name=\"product_imgs[]\"/>&nbsp;<a href=\"javascript:removeline('"+img_index+"');\">删除</a></div>";
      $("#thumb").before(html);
      img_index++;
    }
    //删除行
    function removeline(id){
      $("#thumb_"+id).remove();
    }
    //删除图片
    function removeimg(id){
      $.get("<%=delete_attachment_admin_products_path%>", {id:id}, function (data, textStatus){
        if(data==1){
          $("#img_"+id).remove();
        }else{
          alert("图片删除失败。");
        }
      });
    }
  </script>
<% end %>