config/routes.rb
Mangocms::Application.routes.draw do

  require 'resque/server'
  mount Resque::Server.new, :at => "/resque"

  devise_for :members, :controllers => { :registrations => "members/registrations", :sessions => "members/sessions", :passwords => "members/passwords"}
  # 首页
  root :to => "main#index"

  #网站前台
  #---------------------------------------
  # 用户登录
  match 'sign_in', :to => 'main#list', :channel_id => 'sign_in'
  # 用户注册
  match 'sign_up', :to => 'main#list', :channel_id => 'sign_up'
  # 弹窗登陆
  match 'pop_sign', :to => 'main#list', :channel_id => 'pop_sign'
  # 文章列表页
  match ':channel_id', :to => 'articles#list', :channel_id => /articles/
  # 文章显示页
  match ':channel_id/:id', :to => 'articles#show', :channel_id => /articles/, :id => /\d+/
  # 留言页面
  match 'questions/:channel_id', :to => 'questions#index', :channel_id => /[a-z_]+/
  # 留言提交
  match 'questions/:channel_id/answer_create', :to => 'questions#answer_create', :channel_id => /[a-z_]+/
  # 留言顶一下提交
  match 'questions/:channel_id/answer_top', :to => 'questions#answer_top', :channel_id => /[a-z_]+/
  # 产品列表页
  match 'product/:channel_id', :to => 'products#list', :channel_id => /product/
  # 产品内容页
  match 'product/:channel_id/:id', :to => 'products#show', :channel_id => /product/, :category_id => /[a-z_]+/, :id => /\d+/
  # 产品验证
  match 'service_verifies/verify', :to => 'service_verifies#verify'
  # 产品验证提交
  match 'service_verifies/verify_save', :to => 'service_verifies#verify_save'
  # 前台商城路由
  match 'shop', :to => 'shop_products#index', :channel_id => "shop"
  # 商城列表页
  match ':channel_id/:category_id', :to => 'shop_products#index', :channel_id => /shop/, :category_id => /\d+/
  # 商城内容页
  match ':channel_id/show/:id', :to => 'shop_products#show', :channel_id => /shop/, :id => /\d+/
  # 商城ajax评论
  match '/shop_products/ajax_comments/:id', :to => 'shop_products#ajax_comments', :id => /\d+/
  # 商城ajax购买记录
  match '/shop_products/ajax_buy_logs/:id', :to => 'shop_products#ajax_buy_logs', :id => /\d+/
  # 订单信息内容页
  match "/shop/:channel_id/:id", :to => 'shop_products#order_info', :channel_id => /order_manager/, :id => /\d+/
  #商城搜索
  match "/shop/index/search/:search_condition", :to => "shop/index#search"
  #招聘信息
  match 'zhaopin/:id', :to => 'zhaopins#show', :channel_id => /\d+/
  #栏目地址
  match '/page/:channel_id', :to => 'main#list', :channel_id => /[a-z_]+/
  #内容地址
  match '/page/:channel_id/:id', :to => 'main#show', :channel_id => /[a-z_]+/, :id => /\d+/

  #---------------------------------------
  #文章
  resources :articles
  #前台支付接口
  namespace :payment do
    resources :alipay do
      collection do
        get :get_page
        get :return_page
        post :notify_page
      end
    end
    resources :alipay_secured do
      collection do
        get :get_page
        post :notify_page
      end
    end
    resources :chinabank do
      collection do
        get :get_page
        post :return_page
        post :notify_page
      end
    end
  end

  #用户详细信息路由
  resources :member_infos do
    collection do
      get :edit_info
      post :update_info
      get :judge_member
      get :judge_useremail
    end
  end

  namespace :shop do
    resources :index do
      collection do
        get :search
      end
    end
    resources :products
    resources :cart
  end

  #前台问答
  resources :questions do
    collection do
      post :answer_create
      post :answer_top
    end
  end


  resources :shop_products do
    collection do
      get :list
      get :order_address
      post :submit_order
      get :my_cart   #我的购物车
      get :add_product   #添加商品
      post :buy_product   #立即购买
      get :modify_cart_info   #修改购物车信息
      post :add_order_address  #添加订单收货地址
      delete :destroy_product       #删除产品
      delete :clear_cart            #清楚购物车
      post :delete_order_address  #删除订单地址
      post :generate_order        #生成订单
      post :comment_save
      get :get_address_info
      get :ajax_comments          #异步获取评论
      get :ajax_buy_logs          #异步获取购买记录
    end
    member do
      get :order_info
    end
  end

  resources :logistics do
    collection do
      get :request_logistics
    end
  end

  # 富文本框路径
  mount Ckeditor::Engine => '/ckeditor'
  #服务验证
  resources :service_verifies do
    collection do
      get :verify
      post :verify_save
    end
  end

  #用户中心
  namespace :my do
    resources :orders do
      member do
        get :delete
        get :show
        get :payment
        get :payment_save
      end
    end
  end
  #——-----------------------------------------————————下面是后台路由——————--------------------————————————-------------------——-——————————-
  #cms后台
  #后台管理路由
  namespace :admin do
    #后台用户路由
    resources :members do
      collection do
        post :search
      end
    end

    #后台问题路由
    resources :questions

    #后台回答
    resources :answers do
      collection do
        get  :search
        post :reply_answer_create
        post :batch_operation
      end
      member do
        get :channel_index
        get :answer_admin
        get :ajax_replay_answer_delete
        get :ajax_replay_answer_auth #异步单个审核

      end
    end

    #商品管理
    resources :shop_categories do
      collection do
        get :tree_info    #左侧树信息
      end
      member do
        get :new_category
      end
    end

    #-------------------------招聘信息---------------------------------------------
    resources  :zhaopins do
      collection do
        get  :search
      end
      member do
        get :channel_index
      end
    end

    #-------------------------信息管理---------------------------------------------
    #产品分类管理
    resources :product_categories do
      collection do
        get :tree_info
      end
      member do
        get :new_child
      end
    end


    #产品管理
    resources :products do
      collection do
        get :delete_attachment
        post :frame_add_attachment
        post :delete_product_image
        get  :search
      end
      member do
        get :channel_index
        get :frame_form
        post :attachment
        post :content_create
        get :upload
        get :product_content
      end
    end

    #服务验证管理
    resources :service_verifies do
      collection do
        get :import
        post :import_save
        get :export
        post :export_save
      end
      member do
        get :operation
      end
    end

    #序列号分类管理
    resources :service_categories do

    end

    #文章路由
    resources :articles do
      collection do
        get  :search
        post :delete_product_image
        post :frame_add_attachment
        get :delete_article_image
      end
      member do
        put :update_article
        get :channel_index
        get :frame_form
        get :new_article
      end
    end

    #自定义页面路由
    resources :custom_pages do
      member do
        get :channel_index
        get :link_channel
      end
    end

    #-----------------------------------------------------------------------------
    #商品路由
    resources :shop_products do
      collection do
        post :frame_add_attachment
        post :delete_product_image
        get  :search
      end
      member do
        get :frame_form
        post :attachment
        get :upload
      end
    end


    #套餐路由
    resources :shop_packages do
      collection do
        get :frame_add_attachment
      end
      member do
        get :frame_form
      end
    end
    #订单路由
    resources :shop_orders do
      collection do
        get :export_xls
      end
      member do
        get :preview
      end
    end

    #后台管理员路由
    resources :managers do
      collection do
        get :login
        post :check_login
        get :exists_attach
      end
      member do
        get :modify_password
        post :update_password
        get :logout
      end
    end

    #后台全局变量分类路由
    resources :global_variable_categories do
      collection do
        post :sort
      end
    end

    #后台全局变量路由
    resources :global_variables do
      member do
        get :delete_var
        get :new_image
        get :edit_image
        post :create_image
        post :update_image
      end
      collection do
        post :update_all
        get :exists_attach
      end
    end

    #后台友情链接路由
    resources :friendly_websites

    #后台首页
    resources :main
    #模板管理
    resources :templates do
      member do
        get :default_template
        get :list
      end
    end
    #模板资源文件管理
    resources :skins do
      collection do
        get :upload_file
        post :upload
        get :delete
        get :edit_file
        post :update_file
      end
    end

    #栏目管理
    resources :channels do
      member do
        get :new_child
        get :check_destroy
      end
      collection do
        get :exists_attach
        get :tree_info
        get :template_json_info
      end
    end
    #系统模型管理
    resources :info_models

    #评论管理
    resources :comments do
      collection do
        get :batch_act
      end
    end
  end
end

app/models/skin.rb
#encoding: UTF-8
class Skin
  EDIT_EXTNAME = %w(js css html htm xml txt)
  RAILS_ROOT = "#{Rails.root}/public/"
end

app/controllers/admin/skins_controller.rb
#encoding: UTF-8
class Admin::SkinsController < Admin::BaseController

  
  # 首页
  #
  # 作者: 朱文博
  # 最后更新时间: 2012-4-10
  def index
    @file_list = []
    @dir_list = []
    
    @path = params["path"] if params["path"]
    skin_path = "#{Skin::RAILS_ROOT}#{@path}"
    redirect_skin_index "<#@path>目录不存在."  unless File.exists?(skin_path)
     
    #上级目录地址
    @parent_path = File.dirname(@path) if @path.present?

    Dir["#{skin_path}/*"].each do |f|
      if File.file?(f)
        extname = File.extname(f)
        @file_list << {
          :name => File.basename(f),
          :date => File.ctime(f),
          :size => File.size(f),
          :extname => extname.blank? ? "other" : extname[1..-1]
        }
      end
      if File.directory?(f)
        @dir_list << {
          :name => File.basename(f),
          :date => File.ctime(f),
          :size => Dir["#{f}/*"].size
        }
      end
    end
    
  end

  
  # 上传文件
  #
  # 作者: 朱文博
  # 最后更新时间: 2012-4-10
  def upload_file
    @path = params[:path]
  end

  # 处理上传文件
  #
  # 作者: 朱文博
  # 最后更新时间: 2012-4-10
  def upload
    path = params[:path]
    skin_path = "#{Rails.root}/public/#{path}"
    unless File.exists?(skin_path)
      flash[:error] = "路径错误。"
      redirect_to admin_skins_path and return
    end
    msg = []
    #多文件上传处理
    temp_uplocad = params[:file]
    if temp_uplocad.present?&& temp_uplocad.size>0
      p "*" * 120
      p temp_uplocad
      temp_uplocad.each do |u|
        msg << save_file(u, skin_path)
      end
      flash[:success] = "《#{msg.join("|")}》如果有没上传成功的文件请检查文件名是否重复。"
    else
      flash[:error] = "请选择上传文件。"
    end    
    redirect_to admin_skins_path(:path => path)
  end

  # 编辑文件
  #
  # 作者: 朱文博
  # 最后更新时间: 2012-4-10
  def edit_file
    @path = params[:path]
    @name = params[:name]
    skin_path = "#{Rails.root}/public/#{@path}/#{@name}"
    unless File.exists?(skin_path)
      flash[:notice] = "《#{@name}》 文件不存在。"
      redirect_to admin_skins_path and return
    end
    @extname = File.extname(skin_path)
    File.open(skin_path, "r") do |f|
      @content = f.read
    end
  end

  # 更新文件
  #
  # 作者: 朱文博
  # 最后更新时间: 2012-4-10
  def update_file
    @path = params[:path]
    @name = params[:name]
    skin_path = "#{Rails.root}/public/#{@path}/#{@name}"
    unless File.exists?(skin_path)
      flash[:notice] = "《#{@name}》 文件不存在。"
      redirect_to admin_skins_path and return
    end
    File.open(skin_path, "w") do |f|
      f.write(params[:content])
    end
    flash[:success] = "文件更新成功。"
    redirect_to admin_skins_path(:path => @path)
  end

  # 删除
  #
  # 作者: 朱文博
  # 最后更新时间: 2012-4-10
  def delete
    unless params[:path]||params[:name].present?
      flash[:error] = "文件名或路径错误。"
      redirect_to admin_skins_path and return
    end
    skin_path = "#{Rails.root}/public/#{params[:path]}/#{params[:name]}"
    unless File.exists?(skin_path)
      flash[:notice] = "《#{params[:name]}》 文件不存在。"
      redirect_to admin_skins_path and return
    end
    File.delete(skin_path)
    flash[:success] = "删除操作成功。"
    redirect_to admin_skins_path(:path => params[:path])
  end

  private
  #处理上传文件
  # 作者: 朱文博
  # 最后更新时间: 2012-4-10
   def save_file(file, path)
     if File.exists?("#{path}/#{file.original_filename}")
      return "文件《#{file.original_filename}》重名"
     end
      if !file.original_filename.empty?
        File.open("#{path}/#{file.original_filename}", "wb") do |f|
          f.write(file.read)
        end
        return "#{file.original_filename}上传成功。"
      end
    end

    #跳转到资源管理主页
   # 作者: 佟立家
   # 最后更新时间: 2012-7-16 9:49:55
    def redirect_skin_index(message)
      flash[:notice] =  message
      redirect_to admin_skins_path and return
    end

end

app/helpers/admin/skins_helper.rb
module Admin::SkinsHelper
  #文件单位换算
  #朱文博
  def file_size(size)
    return size if size < 1
    return "%5.2f KB" % (size.to_f/1024) if size < 1024*1024
    "%5.2f MB" % (size.to_f/(1024*1024)) if (size < 1024*1024*1024)
  end

  #文件类型判断
  #朱文博
  def extname_view(ext)
    if ext == ".js"
      "text/javascript"
    elsif ext == ".css"
      "text/css"
    else
      "text/html"
    end
  end

end

app/views/admin/skins/_form.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "template"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/template"%>
<% end %>
<%=content_for :head do%>
  <%= stylesheet_link_tag  "/assets/liquid-codemirror/lib/codemirror.css", "/assets/liquid-codemirror/theme/rubyblue.css" %>
  <%= javascript_include_tag "/assets/liquid-codemirror/lib/codemirror.js", "/assets/liquid-codemirror/mode/xml/xml.js" %>
  <%= javascript_include_tag "/assets/liquid-codemirror/mode/css/css.js", "/assets/liquid-codemirror/mode/javascript/javascript.js" %>
  <%= javascript_include_tag "/assets/liquid-codemirror/mode/htmlmixed/htmlmixed.js"%>
  <%= javascript_include_tag "/assets/liquid-codemirror/jquery.hotkeys.js"%>

  <style type="text/css">
    .CodeMirror {
      border: 1px solid black;
      width: 800px;
    }
    .CodeMirror-scroll {
        height: 500px;
      }
  </style>
  
  <script type="text/javascript">
    $(function(){
      //代码高亮渲染
       var editor = CodeMirror.fromTextArea(document.getElementById("content"), {
          mode: "<%=extname_view(@extname)%>",
          lineNumbers: true
        });
       editor.setOption("theme", "rubyblue");
       $.hotkeys.add('Ctrl+s', function (){$("#form").submit();});
    });    
  </script>
<%end%>
<div class="s-table">
            <table>
              <tbody>
                   <tr>
                      <td width="90">当前文件路径：</td>
                      <td class="picture">
                         <%="#{@path}/#{@name}"%>
                        <%=hidden_field_tag "path", @path%>
                        <%=hidden_field_tag "name", @name%>
                      </td>
                  </tr>
                  <tr>
                      <td><label for="">模板：<br/>（键盘的Ctrl+s可以快速提交。）</label></td>
                      <td>
                        <%= text_area_tag :content, @content, :size => "100x20" %>
                      </td>
                  </tr>
              </tbody>
          </table>
      </div>
      <p>
          <div class="s-input">
              <%=submit_tag "提交"%>
              &nbsp;&nbsp;
              <%=link_to "返回", admin_skins_path(:path => @path)%>
          </div>
      </p>
    

app/views/admin/skins/edit_file.html.erb
    <div class="gm-bloc s-h-wrapper">
        <div class="gm-bloc-head">
            <h3 class="gm-bloc-title">
                编辑文件
            </h3>
            <a href="#" class="toggle"></a>
        </div>
      <%= form_tag update_file_admin_skins_path, :id => "form" do |f| %>
        <%=render "form" %>
      <%end%>
    </div>

app/views/admin/skins/index.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "template"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/template"%>
<% end %>
<div class="gm-tabs s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      模板资源文件管理
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-tabs-content current">
    <div class="gm-toolbar">
      <ul>
        <li><%= link_to "上传文件", upload_file_admin_skins_path(:path => @path) %></li>
        <li><%#= link_to "新建目录", "#" %></li>
        <li><%#= link_to "批量删除", "#" %></li>
      </ul>
    </div>
    <div class="s-table">
      <table>
        <thead>
          <tr>
            <th width="50">选项</th>
            <th>文件名称</th>
            <th width="150">文件大小</th>
            <th width="120">更新时间</th>
            <th width="150">操作</th>
          </tr>
        </thead>
        <tbody>
          <%if @path.present?%>
            <tr>
              <td>&nbsp;</td>
              <td><img src="/assets/file_icon/UpFiles.gif" /> <%=link_to "返回上级目录", (@parent_path.present? ? admin_skins_path(:path => @parent_path) : admin_skins_path)%></td>
              <td colspan="3"><strong>当前路径：</strong><%=@path%></td>
            </tr>
          <%end%>
          <% @dir_list.each do |u| %>          
            <tr>
              <td>
                <div class="s-input">
                  <input type="checkbox" value="<%#=u[:name]%>" />
                </div>
              </td>
              <td><img src="/assets/file_icon/folderclosed.gif" /> <strong><%=link_to u[:name], admin_skins_path(:path => "#{@path}/#{u[:name]}")%></strong></td>
              <td><%=u[:size] == 0 ? "空目录" : "包含#{u[:size]}个文件"%></td>
              <td><%=u[:date].strftime("%Y-%m-%d %H:%M")%></td>
              <td class="edit">
                <%#= link_to "[改名]", "#"%>
                &nbsp;&nbsp;
                <%#= link_to "[删除]", delete_admin_skins_path(:path => @path, :name => u[:name]), :confirm => "您确定要删除吗？" %>
              </td>
            </tr>
          <%end%>
          <% @file_list.each do |u| %>
            <tr>
              <td>
                <div class="s-input">
                  <input type="checkbox" value="<%=u[:name]%>" />
                </div>
              </td>
              <td><img src="/assets/file_icon/<%=u[:extname]%>.gif" />&nbsp;&nbsp;<strong><%=link_to(u[:name], edit_file_admin_skins_path(:path => @path, :name => u[:name])) %></strong></td>
              <td><%=file_size(u[:size])%></td>
              <td><%=u[:date].strftime("%Y-%m-%d %H:%M")%></td>
              <td class="edit">
                <%= link_to("【编辑】", edit_file_admin_skins_path(:path => @path, :name => u[:name])) if Skin::EDIT_EXTNAME.include?(u[:extname]) %>
                &nbsp;&nbsp;
                <!--
                <%#= link_to "[改名]", "#"%>
                &nbsp;&nbsp;
                -->
                <%= link_to "【删除】", delete_admin_skins_path(:path => @path, :name => u[:name]), :confirm => "您确定要删除吗？" %>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/admin/skins/new_file.html.erb
<div class="gm-bloc s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      添加文件
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-bloc-body">
    <%= form_tag create_file_admin_skins_path, :id => "form" do |f| %>
      <%=render "form" %>
    <%end%>
  </div>
</div>

app/views/admin/skins/upload_file.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "template"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/template"%>
<% end %>
<% content_for :head do %>
<script>
  var img_index=0;
  function addline(){
      var html="<tr id=\"tr"+img_index+"\"><td>&nbsp;</td><td><input type=\"file\" name=\"file[]\"/>&nbsp;&nbsp;<a href=\"javascript:removeline('"+img_index+"');\">删除</a></td></tr>";
      $("#line").after(html);
      img_index++;
    }
    //删除行
    function removeline(id){
      $("#tr"+id).remove();
    }
</script>
<%end%>
<div class="gm-bloc s-h-wrapper">
        <div class="gm-bloc-head">
            <h3 class="gm-bloc-title">
                上传文件
            </h3>
            <a href="#" class="toggle"></a>
        </div>
      <%= form_tag upload_admin_skins_path, :id => "form", :multipart => true do |f| %>
        <div class="s-table">
            <table>
              <tbody>
                   <tr>
                      <td width="90">当前文件路径：</td>
                      <td class="picture">
                         <%=@path.blank? ? "跟目录" : @path%>
                        <%=hidden_field_tag "path", @path%>
                      </td>
                  </tr>
                  <tr>
                      <td>上传文件：</td>
                      <td>
                        <input type="button" value="添加上传框" onclick="addline()"/>
                      </td>
                  </tr>
                  <tr id="line">
                      <td>&nbsp;</td>
                      <td>
                        <%= file_field_tag "file[]" %>
                      </td>
                  </tr>
              </tbody>
          </table>
      </div>
      <p>
          <div class="s-input">
              <%=submit_tag "提交"%>
              &nbsp;&nbsp;
              <%=link_to "返回", admin_skins_path(:path => @path)%>
          </div>
      </p>
  <%end%>
</div>