config/routes.rb
Mangocms::Application.routes.draw do

  require 'resque/server'
  mount Resque::Server.new, :at => "/resque"

  devise_for :members, :controllers => { :registrations => "members/registrations", :sessions => "members/sessions", :passwords => "members/passwords"}
  # 首页
  root :to => "main#index"

  #网站前台
  #---------------------------------------
  # 用户登录
  match 'sign_in', :to => 'main#list', :channel_id => 'sign_in'
  # 用户注册
  match 'sign_up', :to => 'main#list', :channel_id => 'sign_up'
  # 弹窗登陆
  match 'pop_sign', :to => 'main#list', :channel_id => 'pop_sign'
  # 文章列表页
  match ':channel_id', :to => 'articles#list', :channel_id => /articles/
  # 文章显示页
  match ':channel_id/:id', :to => 'articles#show', :channel_id => /articles/, :id => /\d+/
  # 留言页面
  match 'questions/:channel_id', :to => 'questions#index', :channel_id => /[a-z_]+/
  # 留言提交
  match 'questions/:channel_id/answer_create', :to => 'questions#answer_create', :channel_id => /[a-z_]+/
  # 留言顶一下提交
  match 'questions/:channel_id/answer_top', :to => 'questions#answer_top', :channel_id => /[a-z_]+/
  # 产品列表页
  match 'product/:channel_id', :to => 'products#list', :channel_id => /product/
  # 产品内容页
  match 'product/:channel_id/:id', :to => 'products#show', :channel_id => /product/, :category_id => /[a-z_]+/, :id => /\d+/
  # 产品验证
  match 'service_verifies/verify', :to => 'service_verifies#verify'
  # 产品验证提交
  match 'service_verifies/verify_save', :to => 'service_verifies#verify_save'
  # 前台商城路由
  match 'shop', :to => 'shop_products#index', :channel_id => "shop"
  # 商城列表页
  match ':channel_id/:category_id', :to => 'shop_products#index', :channel_id => /shop/, :category_id => /\d+/
  # 商城内容页
  match ':channel_id/show/:id', :to => 'shop_products#show', :channel_id => /shop/, :id => /\d+/
  # 商城ajax评论
  match '/shop_products/ajax_comments/:id', :to => 'shop_products#ajax_comments', :id => /\d+/
  # 商城ajax购买记录
  match '/shop_products/ajax_buy_logs/:id', :to => 'shop_products#ajax_buy_logs', :id => /\d+/
  # 订单信息内容页
  match "/shop/:channel_id/:id", :to => 'shop_products#order_info', :channel_id => /order_manager/, :id => /\d+/
  #商城搜索
  match "/shop/index/search/:search_condition", :to => "shop/index#search"
  #招聘信息
  match 'zhaopin/:id', :to => 'zhaopins#show', :channel_id => /\d+/
  #栏目地址
  match '/page/:channel_id', :to => 'main#list', :channel_id => /[a-z_]+/
  #内容地址
  match '/page/:channel_id/:id', :to => 'main#show', :channel_id => /[a-z_]+/, :id => /\d+/

  #---------------------------------------
  #文章
  resources :articles
  #前台支付接口
  namespace :payment do
    resources :alipay do
      collection do
        get :get_page
        get :return_page
        post :notify_page
      end
    end
    resources :alipay_secured do
      collection do
        get :get_page
        post :notify_page
      end
    end
    resources :chinabank do
      collection do
        get :get_page
        post :return_page
        post :notify_page
      end
    end
  end

  #用户详细信息路由
  resources :member_infos do
    collection do
      get :edit_info
      post :update_info
      get :judge_member
      get :judge_useremail
    end
  end

  namespace :shop do
    resources :index do
      collection do
        get :search
      end
    end
    resources :products
    resources :cart
  end

  #前台问答
  resources :questions do
    collection do
      post :answer_create
      post :answer_top
    end
  end


  resources :shop_products do
    collection do
      get :list
      get :order_address
      post :submit_order
      get :my_cart   #我的购物车
      get :add_product   #添加商品
      post :buy_product   #立即购买
      get :modify_cart_info   #修改购物车信息
      post :add_order_address  #添加订单收货地址
      delete :destroy_product       #删除产品
      delete :clear_cart            #清楚购物车
      post :delete_order_address  #删除订单地址
      post :generate_order        #生成订单
      post :comment_save
      get :get_address_info
      get :ajax_comments          #异步获取评论
      get :ajax_buy_logs          #异步获取购买记录
    end
    member do
      get :order_info
    end
  end

  resources :logistics do
    collection do
      get :request_logistics
    end
  end

  # 富文本框路径
  mount Ckeditor::Engine => '/ckeditor'
  #服务验证
  resources :service_verifies do
    collection do
      get :verify
      post :verify_save
    end
  end

  #用户中心
  namespace :my do
    resources :orders do
      member do
        get :delete
        get :show
        get :payment
        get :payment_save
      end
    end
  end
  #——-----------------------------------------————————下面是后台路由——————--------------------————————————-------------------——-——————————-
  #cms后台
  #后台管理路由
  namespace :admin do
    #后台用户路由
    resources :members do
      collection do
        post :search
      end
    end

    #后台问题路由
    resources :questions

    #后台回答
    resources :answers do
      collection do
        get  :search
        post :reply_answer_create
        post :batch_operation
      end
      member do
        get :channel_index
        get :answer_admin
        get :ajax_replay_answer_delete
        get :ajax_replay_answer_auth #异步单个审核

      end
    end

    #商品管理
    resources :shop_categories do
      collection do
        get :tree_info    #左侧树信息
      end
      member do
        get :new_category
      end
    end

    #-------------------------招聘信息---------------------------------------------
    resources  :zhaopins do
      collection do
        get  :search
      end
      member do
        get :channel_index
      end
    end

    #-------------------------信息管理---------------------------------------------
    #产品分类管理
    resources :product_categories do
      collection do
        get :tree_info
      end
      member do
        get :new_child
      end
    end


    #产品管理
    resources :products do
      collection do
        get :delete_attachment
        post :frame_add_attachment
        post :delete_product_image
        get  :search
      end
      member do
        get :channel_index
        get :frame_form
        post :attachment
        post :content_create
        get :upload
        get :product_content
      end
    end

    #服务验证管理
    resources :service_verifies do
      collection do
        get :import
        post :import_save
        get :export
        post :export_save
      end
      member do
        get :operation
      end
    end

    #序列号分类管理
    resources :service_categories do

    end

    #文章路由
    resources :articles do
      collection do
        get  :search
        post :delete_product_image
        post :frame_add_attachment
        get :delete_article_image
      end
      member do
        put :update_article
        get :channel_index
        get :frame_form
        get :new_article
      end
    end

    #自定义页面路由
    resources :custom_pages do
      member do
        get :channel_index
        get :link_channel
      end
    end

    #-----------------------------------------------------------------------------
    #商品路由
    resources :shop_products do
      collection do
        post :frame_add_attachment
        post :delete_product_image
        get  :search
      end
      member do
        get :frame_form
        post :attachment
        get :upload
      end
    end


    #套餐路由
    resources :shop_packages do
      collection do
        get :frame_add_attachment
      end
      member do
        get :frame_form
      end
    end
    #订单路由
    resources :shop_orders do
      collection do
        get :export_xls
      end
      member do
        get :preview
      end
    end

    #后台管理员路由
    resources :managers do
      collection do
        get :login
        post :check_login
        get :exists_attach
      end
      member do
        get :modify_password
        post :update_password
        get :logout
      end
    end

    #后台全局变量分类路由
    resources :global_variable_categories do
      collection do
        post :sort
      end
    end

    #后台全局变量路由
    resources :global_variables do
      member do
        get :delete_var
        get :new_image
        get :edit_image
        post :create_image
        post :update_image
      end
      collection do
        post :update_all
        get :exists_attach
      end
    end

    #后台友情链接路由
    resources :friendly_websites

    #后台首页
    resources :main
    #模板管理
    resources :templates do
      member do
        get :default_template
        get :list
      end
    end
    #模板资源文件管理
    resources :skins do
      collection do
        get :upload_file
        post :upload
        get :delete
        get :edit_file
        post :update_file
      end
    end

    #栏目管理
    resources :channels do
      member do
        get :new_child
        get :check_destroy
      end
      collection do
        get :exists_attach
        get :tree_info
        get :template_json_info
      end
    end
    #系统模型管理
    resources :info_models

    #评论管理
    resources :comments do
      collection do
        get :batch_act
      end
    end
  end
end

app/models/shop_category.rb
#encoding: UTF-8
class ShopCategory < ActiveRecord::Base
  #软删除
  acts_as_paranoid
  
  #自定义URL插件
  extend FriendlyId
  friendly_id :path_customize

  #下级分类
  has_many :children, :class_name => "ShopCategory", :foreign_key => "parent_id", :dependent => :destroy, :order => "position asc, id asc"
  #商品分类关系表
  has_many :shop_product_category_relations , :dependent => :destroy

  #分类节点插件
  acts_as_nested_set
  attr_protected :lft, :rgt
  #排序插件
  acts_as_list
  
  #注册模板字段
  mango_liquid


  #验证文章标题不能重复包括软删除
  validates_as_paranoid
  validates_uniqueness_of_without_deleted :name,   :uniqueness => {:message =>  "商品分类名称不能重复"}
  #倒序查询
  scope :ct_desc , order("created_at DESC")
  scope :ct_asc , order("created_at ASC")

  scope :parent_id,  where(:parent_id  => 1)

  scope :get_cate_id, lambda{|id| where("parent_id =?",id )}

  #是否为父节点
  scope :parent_node , lambda{|mark| where(:parent_node => mark)}
  
  # 通过父类ID获取所有子类别
  #
  # 作者：李季
  # 更新时间：2012-04-23
  
  def self.parent_and_child_categories(parent_id)
    where(:parent_id => parent_id).inject([]) do |arr, category|
      arr << category
      arr << self.where(:parent_id => category.id);arr
    end
  end
  
  
  # 模板标签（cms_ShopCategory）操作数据库方法
  #
  # 作者: 佟立家
  # 最后更新时间: 2012-3-22
  #
  # ==== 参数
  # * <tt>attributes</tt> - 注入参数,对应模板标签参数的hash
  # * <tt>options</tt> - 配置参数
  #
  # ==== 模板示例
  #   {% cms_ShopCategory vo in channel:1 limit:5 recomment:all image:true%}
  #     {{vo.title}}
  #   {% endcms_ShopCategory%}
  #
  #    order 排序
  #    limit 取几条
  #    channel_id 栏目ID
  #
  # ==== 返回
  #   集合<Product>
  #
  def self.cms_liquid_each(attributes, options)
    #设置url
    options[:url] = "/shop_products/${id}"
    #主体
    temp = self.order(attributes["order"] || "created_at DESC")
    temp = temp.where("parent_id = ? ", attributes["cate_id"])  if attributes["cate_id"]
    temp = temp.limit(attributes["limit"])  if attributes["limit"]
    temp = temp.offset(attributes["offset"]) if attributes["offset"]
    temp = temp.select(attributes["column"]) if attributes["column"]
    temp
  end
  
  
end

app/controllers/admin/shop_categories_controller.rb
#encoding: UTF-8
class Admin::ShopCategoriesController < Admin::BaseController


  #首页 异步
  #
  #作者：佟立家
  #更新时间：2012-04-19
  def index
    @shop_categories = ShopCategory.page(params[:page]).per(20)
  end

  #添加分类页面 异步
  #
  #作者：佟立家
  #更新时间：2012-04-19
  def new_category
    @shop_category = ShopCategory.new
    @shop_category.parent_id  = params[:id] if params[:id]
    render  :layout => nil
  end

  #商品分类显示页 异步
  #
  #作者：佟立家
  #更新时间：2012-04-19
  def show
    render  :layout => "iframe"
  end

  #商品分类编辑页 异步
  #
  #作者：佟立家
  #更新时间：2012-04-19
  def edit
    @shop_category = ShopCategory.find params[:id]
    render  :layout => nil
  end



  #商品分类新建页 异步
  #
  #作者：佟立家
  #更新时间：2012-04-19
  def create
    @shop_category  = ShopCategory.new params[:shop_category]
    if @shop_category.save
      flash[:success] = "商品分类保存成功"
     redirect_to admin_shop_products_path
    else
      flash[:errors] = "商品分类保存失败"
      redirect_to :back
    end
  end


  #商品分类更新页 异步
  #
  #作者：佟立家
  #更新时间：2012-04-19
  def update
    @shop_category = ShopCategory.find params[:id]
    if  @shop_category.update_attributes(params[:shop_category])
      flash[:success] = "商品分类更新成功"
      redirect_to admin_shop_products_path
    else
      flash[:errors] = "商品分类更新失败"
      redirect_to :back
    end
  end


  #商品分类删除页 异步
  #
  #作者：佟立家
  #更新时间：2012-04-19
  def destroy
    @shop_category = ShopCategory.find params[:id]
      if  @shop_category.destroy
          flash[:success] = "商品分类删除成功"
          redirect_to admin_shop_products_path
      else
         flash[:errors] = "商品分类删除失败"
         redirect_to :back
      end
       
  end



  #准备左侧树信息
  #
  #作者：佟立家
  #更新时间：2012-04-19
  def tree_info
    tree = []
    if category_id  = params[:id]
      category = ShopCategory.where("parent_id = ?" ,category_id)
    else
      category = ShopCategory.where("id = ?" ,1)
    end
    category.each do |cate|
      url = ""
      url = "/admin/shop_products?category_id=#{cate.id}" if cate.id
      tree << {:id => cate.id, :name => cate.name, :isParent => cate.parent_node, :path_customize => cate.path_customize, :loadURL => url }
    end
    render :json => tree
  end

 
  
end

app/helpers/admin/shop_categories_helper.rb
module Admin::ShopCategoriesHelper
end

app/views/admin/shop_categories/_form.html.erb
 
<!-- form -->
<div class="s-input">
  <%= f.input :parent_id, :as => "select", :collection => nested_set_options(ShopCategory,@shop_category) {|i| "#{'-' * i.level} #{i.name}" }, :label => "上级分类:", :disable => true , :required => false, :include_blank => false%>
  <% if ProductCategory.count == 0 %>
    <span style ="color:red" > 首次添加为根节点   注：不可修改 </span>
  <% end %>
</div>
<br />

<div class="s-input">
  <%= f.input :name, :label => "分类名称:" ,:required => true, :input_html => { :size => "50"} %>
  <p class="help-block"> 分类显示名称</p>
</div>
<br />


<div class="s-input">
  <% if  @shop_category.new_record? %>
    <label class="string required control-label">是否为父级：</label>
    <%= f.check_box :parent_node %>
  <% else %>
  <label class ="string required control-label">节点类型 </label>
   <%= @shop_category.parent_node ? "本分类是父节点不可以添加产品" : "本分类是子节点可以添加产品"   %>
 <% end %>
  <p class="help-block"> 父级分类不可以添加产品</p>
</div>
<br />

<div class="s-input">
  <%= f.input :keyword, :label=>"关键词：" %>
  <p class="help-block">页面的keyword显示</p>
</div>
<br />
<div class="s-input">
  <%= f.input :path_customize, :label=>"自定义url：",:input_html=>{:id=>"path_customize", :class => "required custom_url"} %>
  <p class="help-block">填写拼音或英文单词(可用栏目名称的拼音全称），作用：替代地址上的ID)</p>
</div>
<br />


<div class="s-input">
  <%= f.input :description , :as => "text", :label => "分类描述:" ,:input_html => { :size => "50x5"} %>
  <p class="help-block"> 分类描述，可为空</p>
</div>
<br />

<div class="s-input">
  <%= f.submit "保存" %>
</div>
<br />

<!-- end form -->

app/views/admin/shop_categories/edit.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "shop_category"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/shop_category"%>
<% end %>

<div class="gm-bloc s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      编辑分类信息      <%= link_to "删除本分类", admin_shop_category_path(@shop_category.id), :method => :delete ,:confirm => "你确定要删除吗？" ,:title => "删除"%>
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-bloc-body">
    <%= simple_form_for @shop_category, :url => admin_shop_category_path(@shop_category),:validate => true, :defaults => { :input_html => {:method => :put } } do |f| %>
      <%= render :partial =>"form", :locals =>{:f => f } %>
    <% end %>
  </div>
</div>

<%= content_for :head do   %>
  <script type ="text/javascript">
    $(function(){
      $("#edit_shop_category_<%= @shop_category.id %> ").validate({
        //debug:true,　//测试时打开
        rules: {
          "shop_category[name]": {
            required:true,
            rangelength:[2,30]
          },
          "shop_category[description]": {
            rangelength:[2,200]
          }
        },
        messages:{
          "shop_category[name]": {
            required: "分类标题不能为空",
            rangelength:"描述应在2-30个汉字"
          },
          "shop_category[description]": {
            rangelength:"描述应在2-200个汉字"
          }
        },
        submitHandler:function(form){
          $(form).hide().data('submiting','true');
          var loading = $('<p>正在提交，请稍后...</p>');
          $(form).after(loading);
          form.submit();
        }
      });
    });
  </script>
<% end %>

app/views/admin/shop_categories/index.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "shop_category"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/shop_category"%>
<% end %>

<div class="gm-tabs s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      商品分类管理
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-tabs-head">
    <a href="#"  class="current">分类列表</a>
  </div>
  <div class="gm-tabs-content current">
    <div class="gm-toolbar">
      <ul>
        <li> <%=link_to "添加商品分类", "" , "data-iframe-src" => new_category_admin_shop_product_path, :title => "添加商品" , :class => "add-shop_category" %></li>
      </ul>
    </div>
    <div class="s-table">
      <table>
        <thead>
          <tr>
            <th>选项</th>
            <th>序号</th>
            <th>上级分类</th>
            <th>分类标题</th>
            <th>描述</th>
            <th>更新时间</th>
            <th>创建时间</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <% @shop_categories.each do |category|  %>
            <tr>
              <td>
                <div class="s-input">
                  <input type="checkbox" value="<%= category.id%>" />
                </div>
              </td>
              <td><%=category.id%></td>
              <td> <%=  category.level != 0 ? category.parent.name : ""  %> </td>
              <td><%= category.parent_id.present? ?  "- " * category.level : ""  %>  <%=category.name %> </td>
              <td> <%=category.description %></td>
              <td> <%=current_time_format(category.updated_at) %></td>
              <td> <%=current_time_format(category.created_at) %></td>
              <td class="edit">
                <% if category.parent_id.present? %>
                  <%= link_to image_tag("icon/edit.png"), edit_admin_shop_category_path(category) %>
                  <%= link_to image_tag("icon/delete.png"), admin_shop_category_path(category), :method => :delete ,:confirm => "你确定要删除吗？" %>
                <%end%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="gm-pagination">
      <%= paginate @shop_categories %>
    </div>

  </div>
</div>



<script type="text/javascript">
  $(function(){
    // Document is ready
    $('.gm-tabs').jqtab();
    $('#validBeforePicker,#validAfterPicker').datepick({
      onSelect: customRange});
  });


  function customRange(dates) {
    if (this.id == 'validBeforePicker') {
      $('#validAfterPicker').datepick('option', 'minDate', dates[0] || null);
    }
    else {
      $('#validBeforePicker').datepick('option', 'maxDate', dates[0] || null);
    }
  }

  $.jqmIframe({
    overlay: 70,
    trigger: '.add-shop_category',
    onLoad : $.jqmFullWindow
  });

  function load_content(){
    $('#tree_load_content').load("/admin/showcategories/<%= params[:id] %>/channel_index#{?page=params[:page] if params[:page] }");

  }

  $().ready(function(){
    $(".jqmClose").click(function(){
      load_content();
    });
  })


</script>

app/views/admin/shop_categories/new_category.html.erb
<% content_for :main_menu  do %>
  <%= render :partial => "admin/main/partials/menus/main", :locals => {:menu_type => "shop"} %>
<% end %>
<% content_for :sider_menu  do %>
  <%= render :partial => "admin/main/partials/menus/shop"%>
<% end %>

<div class="gm-bloc s-h-wrapper">
  <div class="gm-bloc-head">
    <h3 class="gm-bloc-title">
      添加商品分类
    </h3>
    <a href="#" class="toggle"></a>
  </div>
  <div class="gm-bloc-body">
    <%= simple_form_for @shop_category,  :url => admin_shop_categories_path,:validate => true  do |f| %>
      <%= render :partial =>"form", :locals =>{:f => f } %>
    <% end %>
  </div>
</div>

  <script type ="text/javascript">
    $(function(){
      $("#new_shop_category").validate({
        //debug:true,　//测试时打开
        rules: {
          "shop_category[name]": {
            required:true,
            rangelength:[2,30]
          },
          "shop_category[description]": {
            rangelength:[2,200]
          }
        },
        messages:{
          "shop_category[name]": {
            required: "商品分类标题不能为空",
            rangelength:"描述应在2-30个汉字"
          },
          "shop_category[description]": {
            rangelength:"描述应在2-200个汉字"
          }
        }
      });
    });

  </script>